import { ITechRecord } from '../../src/models/vehicleTechRecord';

export const generateVehicle = () => ({
  techRecord_primaryVrm: '123',
  techRecord_vin: '123',
  techRecord_vehicleType: 'hgv',
  techRecord_plates_plateReasonForIssue: 'REPLACEMENT',
  techRecord_plates_plateSerialNumber: '1233423452',
  techRecord_brakes_dtpNumber: '',
  techRecord_variantNumber: '',
  techRecord_approvalTypeNumber: 'APPROVAL-TYPE-NUMBER/1234567',
  techRecord_make: '',
  techRecord_model: '',
  techRecord_functionCode: '',
  techRecord_regnDate: '',
  techRecord_manufactureYear: '',
  techRecord_grossGbWeight: '',
  techRecord_grossEecWeight: '',
  techRecord_grossDesignWeight: '',
  techRecord_trainGbWeight: '',
  techRecord_trainEecWeight: '',
  techRecord_trainDesignWeight: '',
  techRecord_maxTrainGbWeight: '',
  techRecord_maxTrainEecWeight: '',
  techRecord_dimensions_length: '',
  techRecord_dimensions_width: '',
  techRecord_tyreUseCode: '',
  techRecord_maxLoadOnCoupling: 123,
  techRecord_frontAxleTo5thWheelCouplingMin: 123,
  techRecord_frontAxleTo5thWheelCouplingMax: 123,
  techRecord_couplingCenterToRearTrlMax: 123,
  techRecord_couplingCenterToRearTrlMin: 123,
  techRecord_speedLimiterMrk: 123,
  techRecord_axles: [
    {
      tyres_tyreSize: '1',
      tyres_plyRating: '2',
      tyres_fitmentCode: '3',
      weights_gbWeight: 123,
      weights_eecWeight: 123,
      weights_designWeight: 123,
    },
  ],
  techRecord_applicantDetails_name: 'Dr T Railer',
  techRecord_applicantDetails_address1: 'Address Line 1',
  techRecord_applicantDetails_address2: 'Address Line 2',
  techRecord_applicantDetails_postTown: 'Postal Town',
  techRecord_applicantDetails_address3: 'Address Line 3',
  techRecord_applicantDetails_postcode: 'PO1 1ST',
} as unknown as ITechRecord);

export const addMiddleware = <ResponseType>(response: ResponseType) => (_, _2) => async (_3) => Promise.resolve({ output: response, response: {} });
